namespace HoloNetwork.Helper {

  public enum HoloNetError {
    NONE,
    CONNECTION_TIMEOUT,
    JOIN_OR_CREATE_ROOM_TIMEOUT,
    JOIN_ROOM_TIMEOUT,
    JOIN_ROOM_FAILED,
    CREATE_ROOM_FAILED,
    JOIN_LOBBY_FAILED,
    JOIN_LOBBY_TIMEOUT,
    JOIN_OR_CREATE_ROOM_FAILED,
    ROOM_DOES_NOT_EXIST,
    ROOM_IS_FULL,
    CONNECT_TO_MASTER_SERVER_TIMEOUT,
    NOT_CONNECTED_TO_PROVIDER,

    ANOTHER_ROOM_OPERATION_IN_PRORESS,

    NOT_CONNECTED_TO_ROOM,

    ANOTHER_NETWORK_OPERATION_IN_PRORESS,

    DISCONNECTED_FROM_PROVIDER,

    PROVIDER_NOT_READY,

    ALREADY_CONNECTED

  }
  
  

}